networks:
  smatech:

services:
  eureka-server:
    image: asheckn/smatech:smatech-eureka
    container_name: eureka-server
    networks:
      - smatech
    ports:
      - "8761:8761"
    restart: unless-stopped

  api-gateway:
    image: asheckn/smatech:smatech-api-gateway
    environment:
      DEFAULT_EUREKA_ZONE: "http://eureka-server:8761/eureka/"
    container_name: api-gateway
    depends_on:
      - eureka-server
    networks:
      - smatech
    ports:
      - "8765:8765"
    restart: unless-stopped

  auth-service:
    image: asheckn/smatech:smatech-auth-service
    container_name: auth-service
    depends_on:
      - postgres
      - eureka-server
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smatech-auth
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_ERROR_INCLUDE_MESSAGE: always
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_PATH: "/swagger"
      WEB_CORS_ALLOWED_ORIGINS: "*"
      WEB_CORS_ALLOWED_METHODS: "GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD"
      WEB_CORS_ALLOWED_HEADERS: "Requestor-Type"
      WEB_CORS_EXPOSED_HEADERS: "X-Get-Header"
      DEFAULT_EUREKA_ZONE: "http://eureka-server:8761/eureka/"
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - smatech

  postgres:
    image: postgres:15
    container_name: smatech-postgres
    environment:
      POSTGRES_DB: smatech-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: unless-stopped
    networks:
      - smatech

  store-service:
    image: asheckn/smatech:smatech-store-service
    container_name: store-service
    depends_on:
      - postgres
      - eureka-server
      - auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smatech-store
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_ERROR_INCLUDE_MESSAGE: always
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_PATH: "/swagger"
      WEB_CORS_ALLOWED_ORIGINS: "*"
      WEB_CORS_ALLOWED_METHODS: "GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD"
      WEB_CORS_ALLOWED_HEADERS: "Requestor-Type"
      WEB_CORS_EXPOSED_HEADERS: "X-Get-Header"
      FOLDER_SAVE_PATH: "/app/uploads/"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      DEFAULT_EUREKA_ZONE: "http://eureka-server:8761/eureka/"
    ports:
      - "8082:8082"
    volumes:
      - app_data:/app/uploads
    restart: unless-stopped
    networks:
      - smatech

  payment-service:
    image: asheckn/smatech:smatech-payment-service
    container_name: payment-service
    depends_on:
      - postgres
      - eureka-server
      - auth-service
      - store-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smatech-payments
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_ERROR_INCLUDE_MESSAGE: always
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_PATH: "/swagger"
      WEB_CORS_ALLOWED_ORIGINS: "*"
      WEB_CORS_ALLOWED_METHODS: "GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD"
      WEB_CORS_ALLOWED_HEADERS: "Requestor-Type"
      WEB_CORS_EXPOSED_HEADERS: "X-Get-Header"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      DEFAULT_EUREKA_ZONE: "http://eureka-server:8761/eureka/"
    ports:
      - "8085:8085"
    restart: unless-stopped
    networks:
      - smatech

  frontend:
    image: asheckn/smatech:smatech-front-service
    depends_on:
      - postgres
      - eureka-server
      - auth-service
      - store-service
      - payment-service
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - smatech

volumes:
  app_data:
  postgres_data: